%sql CREATE TABLE dim_date (	
	[date] DATE PRIMARY KEY,		
	[day] INT,						
	[suffix] VARCHAR(2),			
	[dow_name] VARCHAR(20),			
	[dow_num] INT,					
	[doy] INT,						
	[weekend] INT DEFAULT 0,		
	[woy] INT,						
	[fow] DATE,						
	[low] DATE,						
	[wom] INT,						
	[month] INT,					
	[moy_name] VARCHAR(20),			
	[fom] DATE,						
	[lom] DATE,						
	[gov_quarter] INT,				
	[year] INT,						
	[cy] INT,						
	[fy] INT,						
	[leap_year] INT	DEFAULT 0,		
	[53_weeks] INT DEFAULT 0,		
	[disp_date] VARCHAR(10),		
	[disp_mm_yyyy] VARCHAR(7),		
	[disp_mm_dd_yyyy] VARCHAR(10),	
	[disp_date_suffix] VARCHAR(8),	
	[ppid] INT,						
	[pp] VARCHAR(5),				
	[ppy] INT,						
	[ppn] INT,						
	[ppw] INT,						
	[ppd] INT,						
	[pp_start] DATE,				
	[pp_end] DATE,					
	[pay_day] INT DEFAULT 0,		
	[school_open] INT DEFAULT 0,	
	[school_day] INT DEFAULT 0,		
	[school_ab_day] VARCHAR(1)		
)